[build]
src = "source"
obj = "target/build"
out = "target"
bip = "3.0+"

[build.c]
std = "c11"
hide-symbols = true

[build.cpp]
std = "c++20"
hide-symbols = true

[data]
plug = "bndl"
src = "source/data"
out = "target/sbs.bndl"

[sbs]
exe = "sbs"
lang = "cpp"
dyn-libs = [ "nwge", "nwge_cli", "SDL2" ]

[void]
exe = "void"
lang = "cpp"
dyn-libs = [ "nwge" ]
